### ISSUE TITLE
device detection incorrect for iPad

### ISSUE THREAD

**Issue by mousedown** [tokuda109/next-useragent#173]
This is the parsed output taken from an iPad Pro (11 inch) 13.3.1. It is incorrectly detected as desktop.  Please can you resolve? 

`{"mobile":false,"tablet":false,"desktop":true,"ua":{"browser":"Safari","os":"Mac OS","isMobile":false,"isTablet":false,"isIos":false,"source":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15","osVersion":10,"browserVersion":13,"isIphone":false,"isIpad":false,"isDesktop":true,"isChrome":false,"isFirefox":false,"isSafari":true,"isIE":false,"isMac":true,"isChromeOS":false,"isWindows":false,"isAndroid":false,"isBot":false}}`

**Comment by mousedown** [comment]
I've just read that the UA is the same as a Mac on 13. 

https://stackoverflow.com/questions/9038625/detect-if-device-is-ios

**Comment by tokuda109** [comment]
@mousedown 

This is the correct behaviour of this library, because the useragent strings of iPadOS is same as MacOS.

If you want to detect the iPadOS, you can use the following code:

```
class IndexPage extends React.Component {
  render() {
    const { ua } = this.props

    const isTouchSupport = !!global.window && 'ontouchstart' in global.window
    if (ua.isMac && isTouchSupport) {
      // iPadOS, Safari, Browser side rendering
    } else {
      // Other browser including iPadOS, Safari, Server side rendering
    }
  }
}
```

However, it can not be detected on the server-side, because it can only be detected by useragent strings.
(The iPadOS can not be detected as a tablet from Node.js.)

**Comment by mousedown** [comment]
Thanks
